[tool.black]
line-length = 120
target-version = ['py310']
include = '\\.(py)$'
exclude = '''
/(\.git|\.mypy_cache|\.pytest_cache|build|dist|portable/UserData)/
'''

[tool.isort]
profile = 'black'
line_length = 120
known_first_party = ['app']
